import torch
from detectron2.config import CfgNode
from fvcore.common.param_scheduler import ParamScheduler
import math
from detectron2.solver.lr_scheduler import LRMultiplier, WarmupParamScheduler

class CosineParamSchedulerWithRestart(ParamScheduler):
    """
    Cosine decay or cosine warmup schedules with Restart based on start, restart, and end iter.

    The schedule is an extension of the CosineParamScheduler in fvcore, adding the restarts functionality that it originally lacked. 

    The restart was originally proposed in 'SGDR: Stochastic Gradient Descent with Warm Restarts' (https://arxiv.org/abs/1608.03983).

    Based on it, a constant interval has been added to increase the flexibility of usage. 
    Overall, the learning rate decay curve consists of a constant + cosine decay waveform + 
    cosine decay waveform after 1st restart + cosine decay waveform after 2nd restart + ...

    Example:

        .. code-block:: python

          CosineParamSchedulerWithRestart(iter_per_epoch=cfg.SOLVER.CHECKPOINT_PERIOD, 
                                            start_value=1, 
                                            end_value=end_value,
                                            restart_iter= [1000,3000,10000]
                                            max_iter = 15000,
                                            start_iter=cfg.SOLVER.START_ITER)
    """

    def __init__(
        self,
        iter_per_epoch,
        start_value: float,
        end_value: float,
        restart_iter: list,
        max_iter: float,
        start_iter:float
    ) -> None:
        self.iter_per_epoch = iter_per_epoch
        self._start_value = start_value
        self._end_value = end_value

        restart_iter.append(max_iter) # append max_iter to calculate the cycle of the last cosine descent
        self.restart_iter = restart_iter
        
        self.max_iter = max_iter
        self.start_iter = start_iter
        self.start_epoch = 0

        self.T = self.restart_iter[0]-self.start_iter # Calculate the period of the first cosine decay.
        self.T = self.T/self.iter_per_epoch # Convert to relative value

        # self.start_iter is both the end node of the constant learning rate and the start node of the first 
        # cosine decay, so it must be smaller than the node of the first restart.
        if self.restart_iter[0] >= self.start_iter: 
            self.restart_iter=[self.start_iter]+self.restart_iter
        else:
            assert 1==2

    def __call__(self, where: float) -> float:

        #calculate current epoch
        cur_iter = self.max_iter*where 
        cur_epoch = math.floor(cur_iter / self.iter_per_epoch)

        # Constant interval
        if cur_iter <= self.start_iter:
            return self._start_value

        # Cosine interval
        if cur_iter > self.restart_iter[0]:
            self.start_iter = self.restart_iter[0]
            self.start_epoch = self.start_iter/self.iter_per_epoch # Update the starting node of the current descent cycle
            self.T = (self.restart_iter[1] - self.start_iter)/self.iter_per_epoch # Update the period of current cycle
            self.restart_iter = self.restart_iter[1:] # Remove nodes that have already dropped

        return self._end_value + 0.5 * (self._start_value - self._end_value) * (
            1 + math.cos(math.pi * ((cur_epoch-self.start_epoch)/self.T))
        ) # Set learning rate per epoch


def WarmupCosineRestartLR(
    cfg: CfgNode, optimizer: torch.optim.Optimizer
    ) -> torch.optim.lr_scheduler._LRScheduler:
    
    '''
    Encapsulated in the detectron2 format:

        The current scaling ratio (0~1) is generated by sched, and then the ratio 
        is multiplied with BASE_LR by LRMultiplier to obtain the current LR value.
    
    Note: 
        In the standard Detectron2, lr_scheduler.step() is called after each iteration 
        (refer to LRScheduler.after_step in detectron2/engine/hooks.py). 

        However, it is unreasonable to set different learning rates for samples within 
        different iterations during a single epoch. 

        Therefore, in addition to extending the Restart functionality to CosineLR, it is
        also modified to maintain the same learning rate within each epoch, only reducing
        the learning rate after the completion of each epoch (cfg.SOLVER.CHECKPOINT_PERIOD).
    '''

    end_value = cfg.SOLVER.BASE_LR_END / cfg.SOLVER.BASE_LR
    assert end_value >= 0.0 and end_value <= 1.0, end_value

    
    sched = CosineParamSchedulerWithRestart(# By default, cfg.SOLVER.CHECKPOINT_PERIOD equals the total number of iterations per epoch.
                                            iter_per_epoch=cfg.SOLVER.CHECKPOINT_PERIOD, 

                                            # Set the start_value to 1 to ensure that the initial constant learning rate 
                                            # and decay starting point are always aligned with the BASE_LR in the config,
                                            # reducing the risk of incorrect usage.
                                            start_value=1, 
                                            end_value=end_value,
                                            restart_iter=cfg.SOLVER.RESTART_ITER, # A list containing the nodes for each restart with cosine decay.
                                            max_iter = cfg.SOLVER.MAX_ITER, # Total train iterations
                                            start_iter=cfg.SOLVER.START_ITER # The node where the descent begins, before which the learning rate remains constant.
                                            )
    
    # Same as standard Detectron2
    sched = WarmupParamScheduler(
        sched,
        cfg.SOLVER.WARMUP_FACTOR,
        min(cfg.SOLVER.WARMUP_ITERS / cfg.SOLVER.MAX_ITER, 1.0),
        cfg.SOLVER.WARMUP_METHOD,
        cfg.SOLVER.RESCALE_INTERVAL,
    )

    return LRMultiplier(optimizer, multiplier=sched, max_iter=cfg.SOLVER.MAX_ITER)
