_BASE_: referring_R50.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
    OUT_FEATURES: [res2,res3,res4,res5,lang2,lang3,lang4,lang5]
  WEIGHTS: "models/swin_base_patch4_window12_384_22k.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 16
    LANG_ATT_WEIGHT: 0.1
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    A_WEIGHT : 5.0
    B_WEIGHT : 0.5
    C_WEIGHT : 2.5
    D_WEIGHT : 5.0
    E_WEIGHT : 0.5


TEST:
  EVAL_PERIOD: 2861 #5800
# SOLVER:
#   #LR_SCHEDULER_NAME: WarmupCosineRestartLR
#   IMS_PER_BATCH: 42
#   BASE_LR: 0.00002
#   BASE_LR_END: 5.0e-06
#   RESTART_ITER: 
#   MAX_ITER: 179424
#   CHECKPOINT_PERIOD: 4984
SOLVER:
  #LR_SCHEDULER_NAME: WarmupCosineRestartLR
  IMS_PER_BATCH: 42
  BASE_LR: 0.00002
  GAMMA: 0.5
  STEPS:  (28610,51498,74386) # 27.14 8*1+7*0.5+0.125*5 #(39872,74760,94696,114632) #(39872,79744) #(68928, 97648)  8*1+7*0.5+4*0.25+4+2
  BASE_LR_END: 2.5e-06
  #RESTART_ITER: (23200,52200)
  MAX_ITER: 80108
  CHECKPOINT_PERIOD: 2861
SEED0: 57118786
SEED1: 56276750
SEED2: 59397960
SEED3: 57761635
SEED4: 58796507
SEED5: 58829709


DATASETS:
  TRAIN: ("refcocop_unc_train",)
  TEST: ("refcocop_unc_val",)
